/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserColorPanel.java
 *
 * Created on Mar 17, 2011, 12:55:09 PM
 */

package colors.ui;

import colors.artefacts.NamedColor;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author jjfresh
 */
public class AgentColorPanel extends javax.swing.JPanel {
    private final List<NamedColor> colors = new ArrayList<NamedColor>();

    /** Creates new form UserColorPanel */
    public AgentColorPanel() {
        initComponents();
        setLayout(new FlowLayout(FlowLayout.LEADING));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    public void addColor(final NamedColor color) {
        colors.add(color);
        final JLabel colorLabel = new JLabel(color.getName(), JLabel.CENTER);
        colorLabel.setOpaque(true);
        colorLabel.setBackground(color.getColor());
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                add(colorLabel);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
