/*
 * Fynche - a Framework for Multiagent Computational Creativity
 * Copyright 2011 Josh Hansen
 * 
 * This file is part of the Fynche <https://github.com/joshhansen/fynche>.
 * 
 * Fynche is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * Fynche is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License
 * for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with Fynche.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * If you have inquiries regarding any further use of Fynche, please
 * contact Josh Hansen <http://joshhansen.net/>
 */

/*
 * UserColorPanel.java
 *
 * Created on Mar 17, 2011, 12:55:09 PM
 */

package fynche.ui;

import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import fynche.artefacts.NamedColor;

/**
 *
 * @author Josh Hansen
 */
public class AgentColorPanel extends javax.swing.JPanel {
    private final List<NamedColor> colors = new ArrayList<NamedColor>();

    /** Creates new form UserColorPanel */
    public AgentColorPanel() {
        initComponents();
        setLayout(new FlowLayout(FlowLayout.LEADING));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    public void addColor(final NamedColor color) {
        colors.add(color);
        final JLabel colorLabel = new JLabel(color.getName(), JLabel.CENTER);
        colorLabel.setOpaque(true);
        colorLabel.setBackground(color.getColor());
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                add(colorLabel);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
